CREATE TABLE IF NOT EXISTS PLAYERS (
    ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(24) NOT NULL,
    PASSWORD VARBINARY(61) NOT NULL,
    SEX BOOLEAN NOT NULL,
    AGE TINYINT UNSIGNED NOT NULL,
    MONEY INT NOT NULL DEFAULT 0,
    HEALTH FLOAT NOT NULL DEFAULT 100.0,
    ARMOUR FLOAT NOT NULL DEFAULT 0.0,
    HUNGER FLOAT NOT NULL DEFAULT 0.0,
    THIRST FLOAT NOT NULL DEFAULT 0.0,
    SKIN SMALLINT UNSIGNED NOT NULL,
    POS_X FLOAT NOT NULL,
    POS_Y FLOAT NOT NULL,
    POS_Z FLOAT NOT NULL,
    ANGLE FLOAT NOT NULL,
    VW INT NOT NULL DEFAULT 0,
    INTERIOR TINYINT UNSIGNED NOT NULL DEFAULT 0,

    ADMIN TINYINT UNSIGNED NOT NULL DEFAULT 0,
    SETTINGS INT UNSIGNED NOT NULL DEFAULT 0b0,

    CURRENT_CONNECTION INTEGER UNSIGNED NOT NULL,
    PLAYED_TIME INTEGER UNSIGNED NOT NULL DEFAULT 0,
    LAST_CONNECTION DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

UPDATE `PLAYERS` SET CURRENT_CONNECTION = 0;

CREATE TABLE IF NOT EXISTS CONNECTION_LOGS (
	ACCOUNT_ID INT UNSIGNED NOT NULL,
	IP_ADDRESS VARCHAR(16) NOT NULL,
	DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	FOREIGN KEY(ACCOUNT_ID) REFERENCES PLAYERS(ID) ON DELETE CASCADE
);